version: '3.8'

services:
  backend_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    command: npm start

  frontend_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    command: npm run dev -- --host
